name: Build ArchivesSpace release package

on:
  push:
    branches:
      - master
    tags:
     - v[1-9].[0-9]+.[0-9]+

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: ubi8/ubi
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - uses: actions/checkout@v2
    - name: Install Java
      run: sudo yum -y install java-11-openjdk

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d%H%M')"
    
    - name: Generate tag (build)
      uses: mathieudutour/github-tag-action@v5.3
      id: current_tag
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Bootstrap ArchivesSpace
      run: |
        ./build/run bootstrap

    - name: Build ArchivesSpace release package
      env: 
        VERSION: ${{ steps.get_version.outputs.VERSION }}
      run: ./scripts/build_release ${{ steps.current_tag.outputs.new_version }}

    # LIMITATION: https://github.com/actions/upload-artifact/issues/39
    - name: Upload ArchivesSpace build package
      uses: actions/upload-artifact@v2-preview
      with:
        # github ui generates a zip that will contain the release zip
        name: aspkg-${{ steps.current_tag.outputs.new_version }}
        path: archivesspace-${{ steps.current_tag.outputs.new_version }}.zip
    
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: aspkg-${{ steps.current_tag.outputs.new_version }}
        name: Release - ${{ steps.current_tag.outputs.new_version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
