name: Build ArchivesSpace release package

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: registry.access.redhat.com/ubi8/ubi:8.1
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - uses: actions/checkout@v2
    - name: Install Build Dependencies
      run: |
        yum -y install java-11-openjdk nodejs wget unzip gcc gcc-c++ gcc-gfortran gettext git libtool patch redhat-rpm-config rpm-build make

    - name: Bootstrap ArchivesSpace
      run: |
        ./build/run bootstrap

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d%H%M')"
      if: ${{ !startsWith(github.ref, 'refs/tags/v') }}

    - name: Generate tag (build)
      uses: mathieudutour/github-tag-action@v5.3
      id: current_tag
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        release_branches: .*
        custom_tag: ${{ steps.date.outputs.date }}
      if: ${{ !startsWith(github.ref, 'refs/tags/v') }}

    - name: Build ArchivesSpace release package
      env: 
        VERSION: ${{ steps.current_tag.outputs.new_version }}
      run: |
        echo "./scripts/build_release $VERSION"
        ./scripts/build_release $VERSION
      if: ${{ !startsWith(github.ref, 'refs/tags/v') }}

    - name: Get tag
      id: pushed_tag
      run: echo ::set-output name=new_version::${GITHUB_REF/refs\/tags\//}
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}

    - name: Build ArchivesSpace release package
      env: 
        VERSION: ${{ steps.pushed_tag.outputs.new_version }}
      run: |
        echo "./scripts/build_release $VERSION"
        ./scripts/build_release $VERSION
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}

    # LIMITATION: https://github.com/actions/upload-artifact/issues/39
    - name: Upload ArchivesSpace build package
      uses: actions/upload-artifact@v2-preview
      with:
        # github ui generates a zip that will contain the release zip
        name: aspkg-${{ steps.current_tag.outputs.new_version }}
        path: archivesspace-${{ steps.current_tag.outputs.new_version }}.zip

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: aspkg-${{ steps.current_tag.outputs.new_version }}
        name: Release - ${{ steps.pushed_tag.outputs.new_version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: aspkg-${{ steps.current_tag.outputs.new_version }}
        name: Pre-Release - ${{ steps.current_tag.outputs.new_version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}

