name: Build ArchivesSpace release package

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: registry.access.redhat.com/ubi8/ubi:8.1
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - uses: actions/checkout@v2
    - name: Install Build Dependencies
      run: |
        yum -y install java-11-openjdk nodejs wget unzip gcc gcc-c++ gcc-gfortran gettext git libtool patch redhat-rpm-config rpm-build make

    - name: Bootstrap ArchivesSpace
      run: |
        ./build/run bootstrap

    - name: Get Current Tag
      id: current_github_tag
      run: echo ::set-output name=tag::${GITHUB_TAG#refs/*/}

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d%H%M')"
      if: steps.current_github_tag.outputs.tag != 0
    
    - name: Generate tag (build)
      uses: mathieudutour/github-tag-action@v5.3
      id: new_tag
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      if: steps.current_github_tag.outputs.tag != 0

    - name: Set tag
      id: current_tag
      run:
        if $CURRENT_GITHUB_TAG != 0; then
          echo "::set-output name=tag::${GITHUB_TAG#refs/*/}"
        else
          echo "::set-output name=tag::$NEW_TAG"
      env:
        NEW_TAG: steps.new_tag.outputs.new_version
        CURRENT_GITHUB_TAG: steps.current_github_tag.outputs.tag

    - name: Print tag
      run: echo $TAG
      env:
        TAG: steps.current_tag.outputs.tag

    - name: Build ArchivesSpace release package
      env: 
        VERSION: ${{ steps.get_version.outputs.VERSION }}
      run: ./scripts/build_release ${{ steps.current_tag.outputs.tag }}

    # LIMITATION: https://github.com/actions/upload-artifact/issues/39
    - name: Upload ArchivesSpace build package
      uses: actions/upload-artifact@v2-preview
      with:
        # github ui generates a zip that will contain the release zip
        name: aspkg-${{ steps.current_tag.outputs.new_version }}
        path: archivesspace-${{ steps.current_tag.outputs.new_version }}.zip
    
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: aspkg-${{ steps.current_tag.outputs.new_version }}
        name: Release - ${{ steps.current_tag.outputs.new_version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
