name: Build ArchivesSpace release package

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: registry.access.redhat.com/ubi8/ubi:8.1
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - uses: actions/checkout@v2
    - name: Install Build Dependencies
      run: |
        yum -y install \
                      java-11-openjdk  \
                      nodejs  \
                      wget  \
                      unzip \
                      bison \
                      byacc \
                      cscope \
                      ctags \
                      cvs \
                      diffstat \
                      doxygen \
                      flex \
                      gcc \
                      gcc-c++ \
                      gcc-gfortran \
                      gettext \
                      git \
                      indent \
                      intltool \
                      libtool \
                      patch \
                      patchutils \
                      rcs \
                      redhat-rpm-config \
                      rpm-build \
                      subversion \
                      swig \
                      systemtap

    - name: Bootstrap ArchivesSpace
      run: |
        ./build/run bootstrap

    - name: Get Current Tag
      id: current_github_tag
      run: echo ::set-output name=tag::${GITHUB_TAG#refs/*/}

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d%H%M')"
      if: steps.current_github_tag.outputs.tag != ''
    
    - name: Generate tag (build)
      uses: mathieudutour/github-tag-action@v5.3
      id: current_tag
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      if: steps.current_github_tag.outputs.tag != ''

    - name: Build ArchivesSpace release package
      env: 
        VERSION: ${{ steps.get_version.outputs.VERSION }}
      run: ./scripts/build_release ${{ steps.current_tag.outputs.new_version }}

    # LIMITATION: https://github.com/actions/upload-artifact/issues/39
    - name: Upload ArchivesSpace build package
      uses: actions/upload-artifact@v2-preview
      with:
        # github ui generates a zip that will contain the release zip
        name: aspkg-${{ steps.current_tag.outputs.new_version }}
        path: archivesspace-${{ steps.current_tag.outputs.new_version }}.zip
    
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: aspkg-${{ steps.current_tag.outputs.new_version }}
        name: Release - ${{ steps.current_tag.outputs.new_version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
